[2025-10-14T18:47:14.692+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_project_pipline.create_topic_sensors_sample manual__2025-10-14T18:47:13.618081+00:00 [queued]>
[2025-10-14T18:47:14.699+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_project_pipline.create_topic_sensors_sample manual__2025-10-14T18:47:13.618081+00:00 [queued]>
[2025-10-14T18:47:14.700+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-10-14T18:47:14.710+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): create_topic_sensors_sample> on 2025-10-14 18:47:13.618081+00:00
[2025-10-14T18:47:14.715+0000] {standard_task_runner.py:60} INFO - Started process 984 to run task
[2025-10-14T18:47:14.717+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'pyspark_project_pipline', 'create_topic_sensors_sample', 'manual__2025-10-14T18:47:13.618081+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/pyspark_project_dims.py', '--cfg-path', '/tmp/tmpy6jt3cjl']
[2025-10-14T18:47:14.720+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask create_topic_sensors_sample
[2025-10-14T18:47:14.762+0000] {task_command.py:423} INFO - Running <TaskInstance: pyspark_project_pipline.create_topic_sensors_sample manual__2025-10-14T18:47:13.618081+00:00 [running]> on host f807c778cd29
[2025-10-14T18:47:14.827+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_project_pipline' AIRFLOW_CTX_TASK_ID='create_topic_sensors_sample' AIRFLOW_CTX_EXECUTION_DATE='2025-10-14T18:47:13.618081+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-14T18:47:13.618081+00:00'
[2025-10-14T18:47:16.266+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pyspark_project_dims.py", line 134, in create_topic_sensors_sample
    create_kafka_topic("sensors-sample")
  File "/opt/airflow/dags/pyspark_project_dims.py", line 78, in create_kafka_topic
    existing_topics = [t.strip() for t in topics_list.splitlines()]
AttributeError: 'CompletedProcess' object has no attribute 'splitlines'
[2025-10-14T18:47:16.277+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pyspark_project_pipline, task_id=create_topic_sensors_sample, execution_date=20251014T184713, start_date=20251014T184714, end_date=20251014T184716
[2025-10-14T18:47:16.289+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 22 for task create_topic_sensors_sample ('CompletedProcess' object has no attribute 'splitlines'; 984)
[2025-10-14T18:47:16.334+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-14T18:47:16.354+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
